[bot]
    [bot.logging]
        enabled = true
        level = "info"
    [bot.discord]
        app_id = 295007212638830592
        client_id = 295007212638830592

[api]
    [api.influx]
        enabled = false
        url = "http://localhost:8086"
        db = "test"
    [api.redis]
        enabled = false
